In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LassoLars
from sklearn.metrics import r2_score

In [4]:
#loading the dataset to a pandas Dataframe
sonar_data = pd.read_csv("C:/Users/janan/miniproject/sonardata.csv",header=None)

In [6]:
print(sonar_data.head(10))

       0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
5  0.0286  0.0453  0.0277  0.0174  0.0384  0.0990  0.1201  0.1833  0.2105   
6  0.0317  0.0956  0.1321  0.1408  0.1674  0.1710  0.0731  0.1401  0.2083   
7  0.0519  0.0548  0.0842  0.0319  0.1158  0.0922  0.1027  0.0613  0.1465   
8  0.0223  0.0375  0.0484  0.0475  0.0647  0.0591  0.0753  0.0098  0.0684   
9  0.0164  0.0173  0.0347  0.0070  0.0187  0.0671  0.1056  0.0697  0.0962   

       9   ...      51      52      53      54      55      56      57  \
0  0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1  0

In [7]:
#to check no 0f rowsxcol
sonar_data.shape

(208, 61)

In [8]:
#checking missing values
missing_val= sonar_data.isna().sum().sum()
print("Missing values in sonardataset: \n",missing_val)

Missing values in sonardataset: 
 0


In [9]:
sonar_data[60].value_counts()
# label is not skewed
# Mines -- 111 samples for mines
# Rock -- 97 samples for mines

M    111
R     97
Name: 60, dtype: int64

In [10]:
#Segregating Dependent and Independent features
X =sonar_data .drop(60, axis=1)
y = sonar_data[60]

In [11]:
#Target Varaible Encoding: Converting M,R to 1,0
y = pd.get_dummies(y, drop_first = True) # one column gets dropped (dummy variable trap)
y.sample(5) # R --> 1 and M --> 0

R
3    1
81   1
127  0
25   1
103  0

In [12]:
# distributed of dependent categories
y.value_counts()

R
0    111
1     97
dtype: int64

In [13]:
#from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=1, stratify=y)

In [17]:
X_train.shape, X_test.shape

((156, 60), (52, 60))

In [21]:
pip install tensorflow


  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/80/6f/57d36f6507e432d7fc1956b2e9e8530c5c2d2bfcd8821bcbfae271cd6688/tensorflow-2.14.0-cp311-cp311-win_amd64.whl.metadata
  Using cached tensorflow-2.14.0-cp311-cp311-win_amd64.whl.metadata (3.3 kB)
  Obtaining dependency information for tensorflow-intel==2.14.0 from https://files.pythonhosted.org/packages/ad/6e/1bfe367855dd87467564f7bf9fa14f3b17889988e79598bc37bf18f5ffb6/tensorflow_intel-2.14.0-cp311-cp311-win_amd64.whl.metadata
  Using cached tensorflow_intel-2.14.0-cp311-cp311-win_amd64.whl.metadata (4.8 kB)
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/01/e4/dc0a1dcc4e74e08d7abedab278c795eef54a224363bb18f5692f416d834f/absl_py-2.0.0-py3-none-any.whl.metadata
  Using cached absl_py-2.0.0-py3-none-any.whl.metadata (2.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Obtaining dependency information for flatbuffers>=23.5.26

In [23]:
import tensorflow as tf
from tensorflow import keras

import warnings
warnings.filterwarnings('ignore')

In [24]:
%%time
## Without Dropout
# Defining the architecture of model
model_without_dropout = keras.Sequential([
    keras.layers.Dense(60, input_dim = 60, activation='relu'), # first dense layer
    keras.layers.Dense(30, activation = 'relu'), # second dense layer
    keras.layers.Dense(15, activation = 'relu'), # 3rd dense layer
    keras.layers.Dense(1, activation = 'sigmoid') # output layer
])

model_without_dropout.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

model_without_dropout.fit(X_train, y_train, epochs = 100, batch_size = 8)

Epoch 1/100
20/20 [==============================] - 3s 6ms/step - loss: 0.6985 - accuracy: 0.4487
Epoch 2/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6725 - accuracy: 0.7372
Epoch 3/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6556 - accuracy: 0.7179
Epoch 4/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6258 - accuracy: 0.7564
Epoch 5/100
20/20 [==============================] - 0s 5ms/step - loss: 0.5934 - accuracy: 0.8013
Epoch 6/100
20/20 [==============================] - 0s 5ms/step - loss: 0.5504 - accuracy: 0.7885
Epoch 7/100
20/20 [==============================] - 0s 4ms/step - loss: 0.5134 - accuracy: 0.7692
Epoch 8/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4749 - accuracy: 0.7821
Epoch 9/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4757 - accuracy: 0.8013
Epoch 10/100
20/20 [==============================] - 0s 5ms/step - loss: 0.4287 - accuracy: 0.8205
Epoch 11/

20/20 [==============================] - 0s 5ms/step - loss: 0.0146 - accuracy: 1.0000
Epoch 84/100
20/20 [==============================] - 0s 5ms/step - loss: 0.0103 - accuracy: 1.0000
Epoch 85/100
20/20 [==============================] - 0s 5ms/step - loss: 0.0134 - accuracy: 1.0000
Epoch 86/100
20/20 [==============================] - 0s 5ms/step - loss: 0.0082 - accuracy: 1.0000
Epoch 87/100
20/20 [==============================] - 0s 5ms/step - loss: 0.0097 - accuracy: 1.0000
Epoch 88/100
20/20 [==============================] - 0s 6ms/step - loss: 0.0090 - accuracy: 1.0000
Epoch 89/100
20/20 [==============================] - 0s 6ms/step - loss: 0.0083 - accuracy: 1.0000
Epoch 90/100
20/20 [==============================] - 0s 6ms/step - loss: 0.0066 - accuracy: 1.0000
Epoch 91/100
20/20 [==============================] - 0s 6ms/step - loss: 0.0086 - accuracy: 1.0000
Epoch 92/100
20/20 [==============================] - 0s 6ms/step - loss: 0.0059 - accuracy: 1.0000
Epoch 93/100


In [25]:
# Here we can clearly see an accuracy of 1, which might be because of overfitting
model_without_dropout.evaluate(X_train, y_train)

5/5 [==============================] - 0s 7ms/step - loss: 0.0034 - accuracy: 1.0000


[0.0034418590366840363, 1.0]

In [26]:
# Evaluating without dropout model on test set
model_without_dropout.evaluate(X_test, y_test)

2/2 [==============================] - 0s 25ms/step - loss: 0.9844 - accuracy: 0.7692


[0.9844284057617188, 0.7692307829856873]

In [27]:
## prediction some samples
y_pred = model_without_dropout.predict(X_test).reshape(-1)
print(y_pred[:10])

# round the values to nearest integer i.e., 0 or 1 as the output Activation function was sigmoid (so output values are probabilities)
y_pred = np.round(y_pred)
print(y_pred[:10])

2/2 [==============================] - 0s 16ms/step
[4.4433309e-05 9.5716947e-01 3.8563402e-04 3.4212389e-03 9.1034430e-01
 9.9308300e-01 1.9758287e-05 9.9359649e-01 9.9998367e-01 3.4923600e-05]
[0. 1. 0. 0. 1. 1. 0. 1. 1. 0.]


In [28]:
np.array(y_test[:10]).reshape(1,-1)

array([[0, 0, 1, 1, 0, 0, 0, 1, 1, 0]], dtype=uint8)

In [29]:
np.sum(np.array(y_test[:10]).reshape(1,-1) == y_pred[:10])
# So out of 10, 5 correctly classified

5

In [30]:
# printing the metrics
from sklearn.metrics import confusion_matrix, classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.75      0.78        28
           1       0.73      0.79      0.76        24

    accuracy                           0.77        52
   macro avg       0.77      0.77      0.77        52
weighted avg       0.77      0.77      0.77        52



In [ ]:
#Model with dropout¶

In [31]:
%%time
## With Dropout
# Defining the architecture of model
model_with_dropout = keras.Sequential([
    keras.layers.Dense(60, input_dim = 60, activation='relu'), # first dense layer
    keras.layers.Dropout(0.5),
    
    keras.layers.Dense(30, activation = 'relu'), # second dense layer
    keras.layers.Dropout(0.5),
    
    keras.layers.Dense(15, activation = 'relu'), # 3rd dense layer
    keras.layers.Dropout(0.5),
    
    keras.layers.Dense(1, activation = 'sigmoid') # output layer
])

model_with_dropout.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

model_with_dropout.fit(X_train, y_train, epochs = 100, batch_size = 8)

Epoch 1/100
20/20 [==============================] - 3s 6ms/step - loss: 0.7650 - accuracy: 0.4936
Epoch 2/100
20/20 [==============================] - 0s 5ms/step - loss: 0.7388 - accuracy: 0.4808
Epoch 3/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6899 - accuracy: 0.5769
Epoch 4/100
20/20 [==============================] - 0s 5ms/step - loss: 0.7172 - accuracy: 0.4744
Epoch 5/100
20/20 [==============================] - 0s 5ms/step - loss: 0.7266 - accuracy: 0.4744
Epoch 6/100
20/20 [==============================] - 0s 5ms/step - loss: 0.7095 - accuracy: 0.5641
Epoch 7/100
20/20 [==============================] - 0s 6ms/step - loss: 0.7453 - accuracy: 0.4295
Epoch 8/100
20/20 [==============================] - 0s 5ms/step - loss: 0.6788 - accuracy: 0.5641
Epoch 9/100
20/20 [==============================] - 0s 6ms/step - loss: 0.7012 - accuracy: 0.5449
Epoch 10/100
20/20 [==============================] - 0s 5ms/step - loss: 0.7132 - accuracy: 0.5000
Epoch 11/

20/20 [==============================] - 0s 6ms/step - loss: 0.3982 - accuracy: 0.7821
Epoch 84/100
20/20 [==============================] - 0s 6ms/step - loss: 0.3162 - accuracy: 0.8526
Epoch 85/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3818 - accuracy: 0.8205
Epoch 86/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3887 - accuracy: 0.8269
Epoch 87/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3839 - accuracy: 0.8269
Epoch 88/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3096 - accuracy: 0.8718
Epoch 89/100
20/20 [==============================] - 0s 5ms/step - loss: 0.3634 - accuracy: 0.8782
Epoch 90/100
20/20 [==============================] - 0s 7ms/step - loss: 0.3248 - accuracy: 0.8333
Epoch 91/100
20/20 [==============================] - 0s 7ms/step - loss: 0.3533 - accuracy: 0.8526
Epoch 92/100
20/20 [==============================] - 0s 7ms/step - loss: 0.3184 - accuracy: 0.8397
Epoch 93/100


In [32]:
# evaluating the model on train data
model_with_dropout.evaluate(X_train, y_train)

# the accuracy is not 1, thus less chances of overfitting

5/5 [==============================] - 0s 5ms/step - loss: 0.2034 - accuracy: 0.9295


[0.20339997112751007, 0.9294871687889099]

In [33]:
# evaluating the model on test data
model_with_dropout.evaluate(X_test, y_test)

2/2 [==============================] - 0s 22ms/step - loss: 0.6408 - accuracy: 0.6923


[0.6408462524414062, 0.692307710647583]

In [35]:
#predicting some samples
y_pred = model_with_dropout.predict(X_test).reshape(-1)
print(y_pred[:10])

# round the values to nearest integer ie 0 or 1
y_pred = np.round(y_pred)
print(y_pred[:10])

2/2 [==============================] - 0s 20ms/step
[0.0019052  0.8846138  0.04502625 0.4262237  0.91570914 0.8505101
 0.00233422 0.52813804 0.9976446  0.01383075]
[0. 1. 0. 0. 1. 1. 0. 1. 1. 0.]


In [2]:
np.sum(np.array(y_test[:20]).reshape(1,-1) == y_pred[:20])
# So out of 10, 5 correctly classified

NameError: name 'np' is not defined

In [38]:
 #printing the metrics after dropout
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.80      0.57      0.67        28
           1       0.62      0.83      0.71        24

    accuracy                           0.69        52
   macro avg       0.71      0.70      0.69        52
weighted avg       0.72      0.69      0.69        52

